# Token type
ACCESS_TOKEN = 'access_token'
REFRESH_TOKEN = 'refresh_token'
THRESHOLD = 0.8
TIME_FORMAT_LOG = "[%Y-%b-%d %H:%M]"
# Set response code
ERROR = 500
SUCCESS = 1
USER_EXISTS = 2
USER_FORCE_CHANGE_PASSWORD = 3
USER_NOT_CONFIRM = 4
USER_NOT_EXISTS = 5
EXPIRED = 6
LIMIT_EXCEEDED = 7
CODE_MISMATH = 8

# Set status code
STATUS_SUCCESS = 1
STATUS_FAIL = 2
STATUS_DB_FAIL = 3
